### ISSUE TITLE
Baubley Heart Canisters (bhc) has failed to load correctly

### ISSUE THREAD

**Issue by Tomatoe1** [Traverse-Joe/Baubley-Heart-Canisters#50]
[crash-2022-08-18_21.12.25-fml.txt](https://github.com/Traverse-Joe/Baubley-Heart-Canisters/files/9378739/crash-2022-08-18_21.12.25-fml.txt)

Failure message: Baubley Heart Canisters (bhc) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.19-1.0.0
	Mod Issue URL: https://github.com/Traverse-Joe/Baubley-Heart-Canisters/issues
	Exception message: java.lang.NoSuchFieldError: CONTAINERS

Stacktrace:
	at com.traverse.bhc.common.init.RegistryHandler.<clinit>(RegistryHandler.java:17) ~[baubley-heart-canisters-1.19-1.0.0.jar%23149!/:1.19-1.0.0] {re:classloading}
	at com.traverse.bhc.common.BaubleyHeartCanisters.<init>(BaubleyHeartCanisters.java:52) ~[baubley-heart-canisters-1.19-1.0.0.jar%23149!/:1.19-1.0.0] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.1.0.jar%23198!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.1.0.jar%23197!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

Crash Report UUID: 1f2aa13a-c22c-4868-9edd-0176d43e327d
	FML: 41.1
	Forge: net.minecraftforge:41.1.0

**Comment by BlackWarrior2004** [comment]
+1
https://gist.github.com/BlackWarrior2004/f603d206b967acd994b0323cbc9089d6 <- my crash log

**Comment by Traverse-Joe** [comment]
I need to update to latest forge version in my environment this will be fixed as soon as I can understand I’m now working full time but I will try to get it fixed tonight no promises though thank you for your patience
