### ISSUE TITLE
1.19.2 server crash at launch : failed to load correctly. Forge 43.1.33

### ISSUE THREAD

**Issue by Daltaxy** [Traverse-Joe/Baubley-Heart-Canisters#51]
Hello, my 1.19.2 server crashes at launch. The mod fails to load correctly. Probably due to forge

[07Oct2022 16:03:08.572] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: bhc, class com.traverse.bhc.common.BaubleyHeartCanisters
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:79) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:483) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.1.33.jar%23534!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.1.33.jar%23533!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.NoSuchMethodError: 'void com.traverse.bhc.common.BaubleyHeartCanisters.doClientStuff(net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent)'
	at com.traverse.bhc.common.BaubleyHeartCanisters.<init>(BaubleyHeartCanisters.java:52) ~[baubley-heart-canisters-1.19.2-1.1.2.jar%23161!/:1.19.2-1.1.2]
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
	... 11 more
...............
[07Oct2022 16:03:13.330] [main/ERROR] [net.minecraft.server.Main/FATAL]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Baubley Heart Canisters (bhc) has failed to load correctly
§7java.lang.reflect.InvocationTargetException: null
]

**Comment by Traverse-Joe** [comment]
I will look into this when I get home I may need to update my forge version cause it’s not instancing my main class …. Uhh til I get home can you try using forge 43.1.32 just so I know that is what is the case

**Comment by Traverse-Joe** [comment]
I will look at this when I get home shouldn’t be a hard fix. In the mean time fee free to test Single Player and leave feedback on the new Soul Canister Mechanic

**Comment by Daltaxy** [comment]
> I will look at this when I get home shouldn’t be a hard fix. In the mean time feel free to test Single Player and leave feedback on the new Soul Canister Mechanic

I will, thank you for this mod, I have been waiting for a 1.19.2 port for a long time, I love this mod :)

**Comment by Traverse-Joe** [comment]
Thanks for using it not sure if you are part of my discord but I’m easier to reach for simple questions if needed also post other projects and do community servers for my members to play on
